### ISSUE TITLE
Clean up scatter plot code

### ISSUE THREAD

**Issue by egeerardyn** [matlab2tikz/matlab2tikz#919] opened 2016-06-12 18:27 UTC
Previous TODO from #861:

> ### What needs to be done:
> 
> I think we can clean up the scatter plot stuff a lot by breaking down the different settings into different functions instead of how everything is organized right now (i.e. 1 color vs N colors? 1 size vs N sizes?). That produces a mess to make sure that every property is handled since a property is handled in a few different locations.
> 
> I imagine that we can simplify everything by starting from a basic table output for the data that we want to generate:
> 
> ```
> x y [z] [r] [g] [b] [colorValue] [size]
> ```
> 
> where `[*]` denotes an optional value. Optional in the sense that it can be omitted when it is constant over the whole dataset or when it is not relevant.
> 
> Generating such a table is not that hard, the only special thing is to keep track of which columns are (not) relevant.
> 
> Once the table is taken care of, we can think about telling to `pgfplots`:
> - pick the right marker symbol, and so on,
> - use the column `size` for sizes (or just use the default value)
> - use the columns `r`, `g` and `b` for the color (for a CData matrix)
> - use the column `v` to use the raw colormap
> 
> Each of those bullets can be a separate function, which is well-contained and has a single responsibility.

**Comment by okomarov** [comment] 2016-12-22 21:56
Duplicate of #925. Keeping that one since it's been referred to.

**Closed by okomarov** 2016-12-22 21:56 UTC
Labels: +0.0.1, duplicate, ready-for-action
