### ISSUE TITLE
boxplot labels misplaced

### ISSUE THREAD

**Issue by elm** [matlab2tikz/matlab2tikz#201] opened 2013-05-07 11:49 UTC
If a boxplot is created with group labels the position of this labels is wrong. Matlab reports positions back that are far of the plot. This results in a "Dimension too large." error. See the position of the nodes at the end of the generated tex-file.

Minimal code example:
```matlab
load carsmall;
boxplot(MPG,Origin);
matlab2tikz('boxplottest.tex', 'standalone', true);
```

This may be related: http://www.mathworks.com/matlabcentral/newsreader/view_thread/256242#665916

**Comment by okomarov** [comment] 2015-01-19 21:52
With dac4f2a1b4a502a82ee79251e7d6417b9e577455 cannot reproduce the problem neither under R2014a or b (getPositionOfText has been fixed to handle more unit conversion). Closing.

**Closed by okomarov** 2015-01-19 21:52 UTC
Labels: workaround-exists
