### ISSUE TITLE
pgfplots 1.12 is incompatible with lualatex

### ISSUE THREAD

**Issue by PeterPablo** [matlab2tikz/matlab2tikz#553] opened 2015-02-27 15:45 UTC
See #550, especially this [comment](https://github.com/matlab2tikz/matlab2tikz/pull/550#issuecomment-76357216)

Switching to `xelatex` would require to remove the `\pdfminorversion` statement and review `ACID(47) zplanePlot1`.

**Comment by okomarov** [comment] 2015-02-27 15:52
Also, color-interpolated patches do not render with Lualatex.

**Comment by PeterPablo** [comment] 2015-02-27 15:55
Do you have a pointer to a test case at hand, so we can collect specific issues in a list?

**Comment by egeerardyn** [comment] 2015-02-28 08:42
I think the problem is with the new Lua back-end in `pgfplots 1.12`.
That new back-end is supposed to get the calculations more precise and fast; but it seems that it doesn't support the whole gamut of features in pgfplots.

If I add `\pgfplotsset{lua backend=false}` to the document, `lualatex` is able to compile everything without a problem.

**Comment by PeterPablo** [comment] 2015-02-28 09:10
It says
```However, it only covers parts of the feature set:
some features of pgfplots are unsupported by the lua backend. In this case, it will be switched off
automatically and the TEX implementation will be used as fallback.```

As such, I'd say this is a bug.
`lua backend=false` is a viable workaround. I'll add the label to this issue.

**Comment by egeerardyn** [comment] 2015-03-02 23:30
I've reported this bug to the pgfplots project as [bug 78](https://sourceforge.net/p/pgfplots/bugs/78/).

**Comment by PeterPablo** [comment] 2015-03-09 18:06
What is our course of action? Stick with `lualatex` as the next release of `pgfplots` has this problem fixed?

**Comment by egeerardyn** [comment] 2015-03-31 12:49
We should stick with `lualatex`. Once there is a stable [`pgfplots`](http://pgfplots.sourceforge.net) release with this fix available, we can close this issue.

**Comment by PeterPablo** [comment] 2015-03-31 14:59
What about the [comment](https://github.com/matlab2tikz/matlab2tikz/issues/553#issuecomment-76416410) of @okomarov? (I did not check this myself.)

If we intend to stick to `lualtex`, with what I am fine, then why not close right away? Search will direct here anyhow.

**Comment by egeerardyn** [comment] 2015-03-31 15:40
I prefer to keep it open (i.e. more visible to new users) as long as the dependencies are not easily available to those users. An unstable TDS release is available, but I consider that a bit too difficult to incorporate by most users.

I will have a go at reproducing the bug Oleg talks about and report it to pgfplots.

**Comment by egeerardyn** [comment] 2015-05-27 09:09
There is now a 1.12.1 release available. I have updated the dependency list in our current develop branch to reflect this.

**Closed by egeerardyn** 2015-05-27 09:09 UTC
Labels: dependency-related, workaround-exists

**Comment by PeterPablo** [comment] 2015-05-27 09:12
Did you also check the comment by @okomarov concerning color-interpolated patches?

**Comment by egeerardyn** [comment] 2015-05-27 11:04
I seem to obtain the same results with pdflatex and lualatex, to be honest. Both look somewhat [off](https://dl.dropboxusercontent.com/u/452005/m2t/lualatex.pdf), to be honest.

**Comment by PeterPablo** [comment] 2015-05-27 11:07
Well... yeah :smile: I'd say we ignore this for now. They seem to compile and at least produce some output ;-) May be @okomarov wants to investigate, once he has again more time.
(I'm available in the chat for the next hour and half.)

**Comment by egeerardyn** [comment] 2015-05-27 11:10
I agree. With the limited knowledge I have regarding that kind of plots, I'm not really in the position to touch it. Along with some of our other technical debt issues (e.g. TODOs in the code), I think that's one of the things we have to focus on in the near future: double-check the whole test suite to check whether the output is desired (in addition to reliable) and improve test coverage.

**Comment by PeterPablo** [comment] 2015-05-27 11:11
:+1:
