### ISSUE TITLE
[dev poll] FileExchange GitHub integration: useful or not?

### ISSUE THREAD

**Issue by nschloe** [matlab2tikz/matlab2tikz#598] opened 2015-04-07 09:01 UTC
I'm planning on putting out a release fairly soon, and I'm wondering what your opinion is on the GitHub integration of FileExchange. To sum up, what we get from this is

  * a nice link on www.mathworks.com/matlabcentral/fileexchange/22022-matlab2tikz, listing contributors and such, and
  * daily updates from master.

I think that's it. Especially the last point unsettles me a bit since this means we cannot actually use `master` for development. I pinged MathWorks a couple of times, notifying them of this shortcoming and suggesting a fix in the direction of distributing GitHub releases. Since this didn't work out for several months, I think it's safe to say it won't soon.

Anyhow. What's your take on this? Shall we stick with the GitHub integration or just zip up our releases for distribution?

**Comment by egeerardyn** [comment] 2015-04-07 09:29
I'd wait with a release for the time being, until everything in https://github.com/matlab2tikz/matlab2tikz/milestones/1.0%20Release has been tackled (some of those are underway, can be closed with that 1.0 release or can be tackled within the next week and a half).

I certainly like the idea of GH-FEX integration, unfortunately their implementation is lacking. Right now we do #469, and I'm quite happy with that, although it makes our lives as developers a bit harder (as it's not entirely how GitHub was intended to work). Also, I utterly dislike that people that have subscribed to our FEX updates, get a message every day we have commits (not even against master!). And we've had some "angry customers" because of that, because they thought we were spamming them. In #574, I will also ask about the FEX-GH integration problems. I don't have high hopes for that either, but we can at least try to fight some windmills while we're at it.

Personally, I have been entertaining the idea of doing away with releases and moving more towards continuous delivery. I think with #583 (semver), we could be able to issue releases in far smaller chunks (e.g. 5 PRs) in our current workflow and in the long run move towards continuous releases (and make a formal release at the start of every major or minor version).

**Comment by okomarov** [comment] 2015-04-08 16:03
I am divided on the matter. Hash management has already been taking a fair amount of time away from actual *visual* changes. We might still be at a gain time-wise with respect to the previous visual reviews, however it is becoming fairly frustrating. 

On one hand, I am afraid that continuous delivery might encumber development with version tracking and management. On the other hand, I reckon github integration attracts more collaboration and TMW's interface will eventually get better.

**Comment by PeterPablo** [comment] 2015-04-09 07:32
Personally, I don't see more problems than advantages by rolling releases. If we accidentally commit a breaking change this might easily break people's workflow and cause trouble. Person's who want to live on the bleeding edge can use the develop-branch-zip offered by GitHub or use git directly. I have a feeling that the majority of users strives for stability though, to ease the cumbersome process of exporting figures (we all struggled with Matlab at some point...).

I would stick to #469 for now and manually update the master branch from time to time. A *semver* like release with a lot shorter cycle could be mimicked in addition by creating tags that relate to the develop branch?!

**Comment by egeerardyn** [comment] 2015-10-23 11:36
I'm closing this, since I think we all agreed that nothing should change right now.

**Closed by egeerardyn** 2015-10-23 11:36 UTC
Labels: development
