### ISSUE TITLE
Per-axis user specific options

### ISSUE THREAD

**Issue by jebej** [matlab2tikz/matlab2tikz#844] opened 2016-01-18 19:40 UTC
It would be useful to have the ability to specify axes options per axis (say for subfigures). Right now, the same options are applied to every axes.

**Comment by egeerardyn** [comment] 2016-01-18 19:49
I completely agree. And I have some good news and bad news:
 - There is already a partial implementation of a mechanism that fixes this (see #832).
 - It doesn't work yet for `axes` (hence the partial), but extending that implementation to axes is certainly feasible.

So I'm closing this as a **duplicate of #393/#832**.

**Closed by egeerardyn** 2016-01-18 19:49 UTC
Labels: feature request
