### ISSUE TITLE
Undefined function 'm2tUpdater' for input arguments of type 'char'. 

### ISSUE THREAD

**Issue by FaizSayyid** [matlab2tikz/matlab2tikz#673] opened 2015-05-26 16:30 UTC
When I try to run matlab2tikz() on matlab 2014a I get the following:

>> cleanfigure;
>> matlab2tikz()
 *** (To disable info messages, pass ['showInfo', false] to matlab2tikz.)
 *** (For all other options, type 'help matlab2tikz'.)
 *** 
 *** 
 *** This is matlab2tikz v0.6.0.
 *** 
Undefined function 'm2tUpdater' for input arguments of type 'char'.

Error in matlab2tikz (line 328)
  m2tUpdater(...

Why is this happening?

Thanks

**Comment by egeerardyn** [comment] 2015-05-26 18:05
Duplicate of #674.

**Closed by egeerardyn** 2015-05-26 18:05 UTC
