### ISSUE TITLE
datetick workaround for plot(a,b,c,d)

### ISSUE THREAD

**Issue by Pratched** [matlab2tikz/matlab2tikz#910] opened 2016-05-30 09:04 UTC
Hello again, since the [https://github.com/matlab2tikz/matlab2tikz/wiki/FAQ#time-series-plot-raises-dimension-too-large-tex-error)] workaround for the datetick issue using m2t is pretty helpfull I tried to use it for plotting to different graphs with different x-vectors. The problem probably is made up by  `unique` since this just creates following numbers.

I tried to create a minimal example to explain what I am talking about.
```
dta = linspace(now(),now()+0.1,100);
dtb= linspace(now()+0.07,now()+0.09,10);
aa  = cumsum(randn(100,1));
bb  = cumsum(randn(10,1));
% Re-map dates and re-plot
[~,~,a] = unique(dta);
[~,~,b] = unique(dtb);
plot(a,aa,b,bb)

% Choose number of ticks and format of labels
numticks = 7;
fmt      = 'hh:MM';

% Set manually
ticks  = linspace(a(1),a(end),numticks);
labels = datestr(linspace(min(dta)max(dta),numticks), fmt);
set(gca, 'xtick',ticks, 'XTickLabel',labels)
```

dta and dtb dont start at the same time and will each have a different amount of time between a new line.
I could just add some lines in b  and bb but since my real a- and aa-vectores are about 1500 lines b and bb are only 177 this would not be a very pleseant work. 
Especially while I did got a value in aa avery minute (so dta has a line for every minute) and in bb there is a new line "created" every 5 minutes (so dtb has a new line every 5 minutes) I woul have to interpolate for 4 new lines in bb betwenn each actual line.

I hope you do get what I am trying to tell you. Thanks in advance for any solution;)

**Comment by miscco** [comment] 2016-05-30 09:32
I intend to finish #907 this week, so that all that unique shenanigans should not be necessary and cleanfigure handles it by normalizing the respective axis.

If you are in a hurry you can try the PR right now, as it should work already.

**Comment by miscco** [comment] 2016-05-30 09:37
I think the problem is, that the workaround is not really suitable. Have you tried creating a x axis in the respective granularity?

so if your data goes from 0min to Nmin use 
```matlab
t1 = linspace(0, N, NumberofSamples_DataA)
t2 = linsapce(0,N, NumberofSamples_DataB)
```

Obviously if one of the data series (say DataA e.g) does not fill the whole time range you can always adjust by 

```matlab
t1 = [0, linspace(start_A, end_A, NumberofSamples_DataA), N];
DataA = [NaN; DataA; NaN];
```

you can still redefine the ticklabels etc via set

**Comment by okomarov** [comment] 2016-05-30 17:18
Thanks for bringing this to our attention, I updated the FAQ with an example with two time-series. I will close this issue but feel free to reopen if the need arises.

**Closed by okomarov** 2016-05-30 17:18 UTC

**Comment by Pratched** [comment] 2016-05-31 10:10
Thanks, that worked quite well. Problem is, there is no x axis description at all. This is the minimal example I created with xour workaround. This problem keeps happening to my real script as well. Maybe i did set the ticks wrong?

```
% Sample data with two time-series
%dta = linspace(now(),now()+0.1,100);
%dtb = linspace(now()+0.07,now()+0.09,10);
%a   = cumsum(randn(100,1));
%b   = cumsum(randn(10,1));

% Map to unique time-vector
dt       = union(dta,dtb);
[~,posa] = ismember(dta,dt);
[~,posb] = ismember(dtb,dt);

plot(posa',a, posb',b)

% Choose number of ticks and format of labels
numticks = 7;
fmt      = 'hh:MM';

% Set manually
ticksa  = linspace(dta(1),dta(end),numticks);
labelsa = datestr(linspace(min(dta),max(dta),numticks), fmt);
set(gca, 'xtick',ticksa, 'XTickLabel',labelsa)
%ticksb  = linspace(dtb(1),dtb(end),numticks);
%labelsb = datestr(linspace(min(dtb),max(dtb),numticks), fmt);
%set(gca, 'xtick',ticksb, 'XTickLabel',labelsb)
```

**Comment by Pratched** [comment] 2016-05-31 11:20
@miscco I tried PR (if this means to change clanfigure.m-script like you did in #907 )but couldn fix the problem.
