### ISSUE TITLE
Stacked bar plots: errors after #851

### ISSUE THREAD

**Issue by twippenbeck** [matlab2tikz/matlab2tikz#901] opened 2016-05-17 12:35 UTC
merge #900 destroys stacked bar plots in current development version

MWE from matlab doc:

    figure;
    
    y = [2 2 3; 2 5 6; 2 8 9; 2 11 12];
    bar(y,'stacked')
    
    matlab2tikz(...
                'filename','MWE_merge900.tex',...
                'encoding','UTF-8',...
                'standalone',true...
                );

Output with current dev version:
![mwe_merge900](https://cloud.githubusercontent.com/assets/14804753/15322332/6de9f108-1c3c-11e6-9341-299ca3774a89.png)

**Comment by miscco** [comment] 2016-05-17 12:40
Ok so i think this is not related to #900 but #851, which was also merged yesterday. That PR fixed problems with barplots raised by #845 and #840.

For me your working example is compiling fine. However, this requires a more recent version of pgfplots (as expressed by the accompanied warning). Could you please check your pgfplots version?

**Comment by miscco** [comment] 2016-05-17 12:44
BTW you can find the latest version here https://sourceforge.net/projects/pgfplots/

**Comment by egeerardyn** [comment] 2016-05-17 12:49
I can reproduce the issue here using R2014b.

The problem is indeed not from the #900 side of the merge, but rather from the side of c13f18c.

This is **not** related to the pgfplots version (I am using `Package: pgfplots 2016/01/06 v1.13 Data Visualization (1.13)` which is the latest for TeXLive 2015 and the latest stable release).

**Comment by miscco** [comment] 2016-05-17 12:50
Could you post the resulting tex file?

For me it compiles fine and as far as i understand there should be a test for that.

**Comment by egeerardyn** [comment] 2016-05-17 12:53
Running the MWE above from c13f18c produces: 
```latex
% This file was created by matlab2tikz.
%
%The latest updates can be retrieved from
%  http://www.mathworks.com/matlabcentral/fileexchange/22022-matlab2tikz-matlab2tikz
%where you can also make suggestions and rate matlab2tikz.
%
\documentclass[tikz]{standalone}
\usepackage[T1]{fontenc}
\usepackage[utf8]{inputenc}
\usepackage{pgfplots}
\usepackage{grffile}
\pgfplotsset{compat=newest}
\usetikzlibrary{plotmarks}
\usetikzlibrary{arrows.meta}
\usepgfplotslibrary{patchplots}
\usepackage{amsmath}

\begin{document}
\definecolor{mycolor1}{rgb}{0.20810,0.16630,0.52920}%
\definecolor{mycolor2}{rgb}{0.21783,0.72504,0.61926}%
\definecolor{mycolor3}{rgb}{0.97630,0.98310,0.05380}%
%
\begin{tikzpicture}

\begin{axis}[%
width=6.028in,
height=4.754in,
at={(1.011in,0.642in)},
scale only axis,
bar shift auto,
bar width=0.8,
xmin=0.5,
xmax=4.5,
xtick={1, 2, 3, 4},
ymin=0,
ymax=25,
axis background/.style={fill=white}
]
\addplot[ybar stacked,fill=mycolor1,draw=black,area legend] plot table[row sep=crcr] {%
1	2\\
2	2\\
3	2\\
4	2\\
};
\addplot[forget plot,color=white!15!black] table[row sep=crcr] {%
0.5	0\\
4.5	0\\
};
\addplot[ybar stacked,fill=mycolor2,draw=black,area legend] plot table[row sep=crcr] {%
1	2\\
2	5\\
3	8\\
4	11\\
};
\addplot[forget plot,color=white!15!black] table[row sep=crcr] {%
0.5	0\\
4.5	0\\
};
\addplot[ybar stacked,fill=mycolor3,draw=black,area legend] plot table[row sep=crcr] {%
1	3\\
2	6\\
3	9\\
4	12\\
};
\addplot[forget plot,color=white!15!black] table[row sep=crcr] {%
0.5	0\\
4.5	0\\
};
\end{axis}
\end{tikzpicture}%
\end{document}
```

**Comment by miscco** [comment] 2016-05-17 13:04
Ok cudos from me, that is indeed an error. I cant explain why the test suite didnt caught this but I have found a fix for it.

**Comment by miscco** [comment] 2016-05-17 13:09
@twippenbeck Thanks for reporting this, somehow the stacked bar plots never raised errors. Sadly i was on the wrong branch, that was not rebased on the current head, so i could not reproduce it.

**Comment by miscco** [comment] 2016-05-19 19:43
With the fix merged i am closing this. Sorry for the bug

**Closed by miscco** 2016-05-19 19:43 UTC
Labels: ready-for-action
