### ISSUE TITLE
Math symbol not escaped in boxplot

### ISSUE THREAD

**Issue by danjjl** [matlab2tikz/matlab2tikz#717] opened 2015-08-06 19:46 UTC
# Minimal MATLAB working example:
```matlab
boxplot([1;2])
ylabel('0 > 2')
matlab2tikz('bug.tex')
```

# matlab2tikz .tex output
```tex
...
ylabel={0 > 2},
...
```

# Expected .tex output
```tex
...
ylabel={$\text{0 \textgreater{} 2}$},
...
```

The > symbol should be escaped.

*(output could be simpler; copied it from matlab2tikz output for normal plot)*
*(percent symbol works as expected)*

*(using commit d7f60de186ace08156df276441c357ec6266c3ea)*

**Comment by egeerardyn** [comment] 2015-08-06 19:55
I cannot reproduce this in R2014a nor R2014b from within the `develop` branch, so I presume you are using the `master` branch?

Could you please provide more information on the environment you are using:
- version of MATLAB, and
- git commit used?

**Comment by danjjl** [comment] 2015-08-06 21:33
I am running MATLAB 2015a

**Comment by egeerardyn** [comment] 2015-08-07 07:43
I can reproduce the bug in R2015a (not in R2014b unfortunately).

**Comment by egeerardyn** [comment] 2015-08-07 08:20
As I look at it, it seems desired behavior, although it is somewhat odd to see such big differences between two successive releases.

Let me explain.
Up to R2014b, the interpreter used for those labels, seems to be `tex`. This is MATLAB's own subset of the LaTeX language and passes through their own typesetting engine. Typically this is used for formulas (but without any `$` as you would expect in normal LaTeX).

In R2015a, apparently, the interpreter for those labels has been changed to `none` (which it shouldn't have), i.e. no LaTeX substitutions are performed (so a `_` should appear as an underscore, not a subscript). For that interpreter, the only thing we do is escape reserved LaTeX symbols (e.g. `%`, `\`, `#`, `$`, ...).

So I think this is an R2015a regression rather than a bug in `matlab2tikz`.
You will get the old behavior back if you set `set(ylabel(...), 'interpreter', 'tex')`.
According to the [MATLAB documentation](http://nl.mathworks.com/help/matlab/ref/ylabel.html#input_argument_namevalue_interpreter), however, that should be the default setting but for one reason or another, it is not in R2015a.

**Comment by danjjl** [comment] 2015-08-07 14:46
Thank you for your investigation.
I have filed a service request with the MathWorks team.

**Comment by egeerardyn** [comment] 2015-08-07 17:39
Thank you for filing the report with TMW. I tried a to investigate a bit further into what has changed to `boxplot` since R2014b, but the changes to `boxplot` itself were unrelated. I didn't investigate further into the functions it calls to see what has changed. But I presume that the same problem might occur with other plots as well.

**Comment by danjjl** [comment] 2015-08-10 14:27
I have received an answer from the MathWorks team.

They acknowledge the issue and have a fix ready for MATLAB 2015b.

In the meantime adding the following lines to `startup.m` solves the problem:

```matlab
set(groot,'DefaultTextInterpreter','tex');
set(groot,'DefaultTextInterpreterMode','manual');
```

**Comment by egeerardyn** [comment] 2015-08-10 14:32
Thank you for getting back to us with this fix! I will close this issue since there is a perfectly viable workaround which doesn't require more than a fix in `startup` :+1:

**Closed by egeerardyn** 2015-08-10 14:32 UTC
Labels: +0.0.1, dependency-related, HG2-R2015a, text, workaround-exists
