### ISSUE TITLE
cleanfigure hides axis labels in matlab figure

### ISSUE THREAD

**Issue by jonasp1** [matlab2tikz/matlab2tikz#230] opened 2013-09-17 14:48 UTC
```
figure();
plot(rand(100,1));
xlabel('this label will dissapear in the matlab window');
cleanfigure();
matlab2tikz('label_appears_again.tikz');
```

The label dissapears in the matlab figure after the cleanfigure command. Nevertheless it comes back in the tikz file.

**Comment by okomarov** [comment] 2015-01-19 22:00
As of dac4f2a1b4a502a82ee79251e7d6417b9e577455 cannot reproduce the issue neither on Matlab R2014a/b or Octave 3.8.2. Closing.

**Closed by okomarov** 2015-01-19 22:00 UTC
Labels: cleanfigure
