### ISSUE TITLE
When `parseStringsAsMath` is set, underscores are parsed as \_

### ISSUE THREAD

**Issue by rezahousseini** [matlab2tikz/matlab2tikz#891] opened 2016-04-28 06:34 UTC
When 'parseStringsAsMath' is set to true, an underscore gets replaced by \_ and underscore symbols in math mode are not handled correctly.
For example an legend as `$x_2$` gets replaced by `$x\\_2$`.

**Comment by okomarov** [comment] 2016-04-28 14:33
I guess you meant _$x_2$ gets replaced by $x\_2$._ ?

**Comment by egeerardyn** [comment] 2016-04-28 16:27
Could you provide bit of MATLAB code to reproduce this? I **cannot reproduce** your problem here with that little information...

I have used:
 - both R2014a and R2016a (I have no reason to believe intermediate versions behave differently, everything old is unsupported)
 - latest `develop` branch (`master` should not behave differently, I think: the parsing code has not changed in ages; and otherwise the fix is simple: use develop)
with the following code:

```matlab
plot(1:10)
legend('$x_2$')
matlab2tikz('issue891.tex','parseStringsAsMath',true,'standalone',true);
```

The output contains
```latex
\addlegendentry{$\text{\$x}_2\text{\$}$};
```

Admittedly, this is probably now what you want, but it looks just fine in the compiled output:
<img width="209" alt="screen shot 2016-04-28 at 18 26 54" src="https://cloud.githubusercontent.com/assets/177360/14893232/d373cd32-0d6e-11e6-9b7a-b1a16c3e215d.png">

But the `parseStringsAsMath` is meant to work when you do NOT add the `$` yourself.

So the MWE with `legend('x_2')` does produce `\addlegendentry{$x_2$};` for both R2014a and R2016a here.

**Comment by egeerardyn** [comment] 2016-05-04 16:06
I'm closing this as I cannot reproduce this. If you are still having problems with this, feel free to re-open if you have an MWE (and info about which MATLAB/Octave/... you are using) such that we can try to reproduce the problem.

**Closed by egeerardyn** 2016-05-04 16:06 UTC
Labels: cannot reproduce
