### ISSUE TITLE
Stacked bar charts

### ISSUE THREAD

**Issue by redfixie** [matlab2tikz/matlab2tikz#845] opened 2016-01-19 10:00 UTC
Hi - Stacked bar charts don't compile correctly, the last 'stack' goes on top of all others. In order to create stacked bar charts after 
*\begin{axis}[%*
you must add the line
*ybar stacked,*

**Comment by egeerardyn** [comment] 2016-01-19 10:23
Thank you for reporting this.
Do you by any chance have a piece of MATLAB code to reproduce this and a screenshot of what you are seeing?

I'm going on a limp here, but I think your version of `pgfplots` might be somewhat outdated. I.e. `matlab2tikz` should already be able to reproduce stacked plots as you see below:
<img width="1114" alt="screen shot 2016-01-19 at 11 08 33" src="https://cloud.githubusercontent.com/assets/177360/12415663/3cc7b0da-be9d-11e5-8794-32411b19dee3.png">
You should be able to reproduce the right plot by going into the directory `test/suites` within your matlab2tikz installation, run `ACID(34)` and then `matlab2tikz` on that figure (you can use the flags `'standalone',true` for easier compilation).

So can you also check the version of the software you are using?
 - matlab2tikz (this gets output to the terminal during execution),
 - MATLAB(type `version` in MATLAB),
 - pgfplots, by compiling the following document with LaTeX:
```latex
\documentclass{standalone}
\usepackage{tikz,pgfplots}
\begin{document}
TikZ: \expandafter\csname ver@tikz.sty\endcsname \\
pgfplots: \expandafter\csname ver@pgfplots.sty\endcsname \\
\end{document}
```
That should produce a document that looks like
<img width="345" alt="untitled" src="https://cloud.githubusercontent.com/assets/177360/12415816/164d1426-be9e-11e5-8d02-020e09b7a6c9.png">

**Comment by egeerardyn** [comment] 2016-02-08 19:59
Since this is likely a problem with an outdated pgfplots version, I will close this. 
If you are using a recent version of pgfplots and still have this issue, feel free to reopen.

**Closed by egeerardyn** 2016-02-08 19:59 UTC
Labels: deprecated
