### ISSUE TITLE
Grid size of tex file from Matlab2tikz 

### ISSUE THREAD

**Issue by YangAooo** [matlab2tikz/matlab2tikz#1104] opened 2022-01-06 19:09 UTC
Hello,

I recently started using Matlab2tikz and ran into some problems.
I use the command `grid  on` in matlab, and the grid size of the graph from the tex file is too small and different from matlab figure. How can I change it ?
In addition, when I run the command 'matlab2tikz ('myfile.tex') ', there are always a warning said "You will need pgfplots version 1.3 or newer to compile the tikz output", but the automatically generated tex file is work, Is this a problem?

Thank you very much!

**Comment by egeerardyn** [comment] 2022-01-06 20:27
That message regarding the pgfplots version is just for your information: if you are using an old version of pgfplots it will not work.

Regarding the grid size: it is very well possible that the grid size is different between MATLAB and pgfplots. To avoid that, it should be enough to specifically set the grid size in MATLAB (unfortunately, I cannot give you the right code to do that by hand, but e.g. using `edit plot` in the figure, it should be possible.

The general guiding principle in matlab2tikz is that we do NOT try to mimic how a plot looks in MATLAB, but rather try to understand what a user tried to accomplish. E.g. when you do `grid on`, that signals you want a grid. MATLAB picks a grid size automatically. What matlab2tikz does is also enable the grid, but which exact grid size gets left to pgfplots to decide.
The way to circumvent that behavior is:
- to set the relevant option (e.g. grid size) explicitly in MATLAB; or 
- to call matlab2tikz with the strict option: `matlab2tikz(..., 'strict', true)`.  

I will close this issue, since both items are expected behavior.

**Closed by egeerardyn** 2022-01-06 20:27 UTC
