### ISSUE TITLE
Plot with markers but no line

### ISSUE THREAD

**Issue by Kaniee** [matlab2tikz/matlab2tikz#1050] opened 2019-03-03 20:36 UTC
When I plot data with markers but no line it will appear in the legend with a line.
I created a MWE:
`plot([0, 1], [1, 1], 'Marker', 'o', 'LineStyle', 'none')
legend`
The difference between MATLAB and tikz is shown in the attached files.
![image](https://user-images.githubusercontent.com/48187781/53701321-036c6880-3dfc-11e9-85ca-e5af0cc45486.png)
![image](https://user-images.githubusercontent.com/48187781/53701326-1bdc8300-3dfc-11e9-848f-667bda6929f2.png)

In `\addplot` it should be `only marks` instead of `draw=none`.

**Comment by egeerardyn** [comment] 2019-03-04 21:49
This looks like a duplicate of #1035 which has already been merged into develop.

**Closed by egeerardyn** 2019-03-04 21:49 UTC
